language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules

env:
  global:
    - CC_TEST_REPORTER_ID=1122ef750ef2edec7ac24fbd19210b60ce0fd5ddcb85fee90d1c0aef77f1984c
    - NODE_ENV=test

notifications:
  email: false

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wallet_test;'

install:
  - npm install

before_script:
  - echo "Enu Gbe Wallet"

script:
  - npm test
